kumuluzee:
  name: rso-support_tickets
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8087
    http:
      port: 8087
  datasources:
    - jndi-name: jdbc/SupportTicketsDS
      connection-url: jdbc:postgresql://172.17.0.1:33340/support_ticket
      username: dbuser
      password: postgres
      max-pool-size: 20
  discovery:
    etcd:
      hosts: http://172.17.0.1:2379
  config:
    etcd:
      hosts: http://172.17.0.1:2379
  health:
    checks:
      data-source-health-check:
        jndi-name: jdbc/SupportTicketsDS
  cors-filter:
    servlet:
      allow-origin: "*"
  metrics:
    web-instrumentation:
      - name: support_tickets-endpoint
        url-pattern: /v1/support_tickets/*
  logs:
    config-file: '<?xml version="1.0" encoding="UTF-8"?>
                  <Configuration name="orders">
                      <Appenders>
                          <Console name="console" target="SYSTEM_OUT">
                              <PatternLayout pattern="%d %p %marker %m %X %ex %n"/>
                          </Console>
                          <!--<Socket name="logstash" host="85ebe26b-3a39-4754-8516-d8d6be2f154f-ls.logit.io"
                          port="21183"
                                                               protocol="tcp">
                              <JSONLayout complete="false" compact="true" eventEol="true" charset="UTF-8" properties="true"/>
                          </Socket>-->
                      </Appenders>
                      <Loggers>
                          <!-- Default logger -->
                          <Root level="all">
                              <AppenderRef ref="console" level="info"/>
                              <!--<AppenderRef ref="logstash" level="trace"/>-->
                          </Root>
                      </Loggers>
                  </Configuration>'
rest-properties:
  healthy: true
