apiVersion: v1
kind: Service
metadata:
  name: support_tickets
  labels:
    app: support_tickets
spec:
  type: NodePort
  ports:
  - name: server
    port: 8087
    protocol: TCP
    targetPort: 8087
  selector:
    app: support_tickets
