apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: support-tickets-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: support-tickets
    spec:
      containers:
      - image: ggrex/rsobnb-support_tickets:0.1
        imagePullPolicy: Always
        name: support-tickets
        env:
          - name: KUMULUZEE_DISCOVERY_CLUSTER
            value: bluemix
          - name: KUMULUZEE_DISCOVERY_ETCD_HOSTS
            value: http://etcd:2379
          - name: KUMULUZEE_CONFIG_ETCD_HOSTS
            value: http://etcd:2379
          - name: KUMULUZEE_DATASOURCES0_CONNECTIONURL
            value: jdbc:postgresql://postgres-support-tickets:5432/support_ticket
          - name: KUMULUZEE_SERVER_BASEURL
            value: http://169.51.13.134:30477
        livenessProbe:
          httpGet:
            path: /health
            port: server
          initialDelaySeconds: 20
          periodSeconds: 3
        ports:
        - containerPort: 8087
          name: server
          protocol: TCP